version: '3'
services:
#mssql docker
  ekino-sql-mr:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    restart: unless-stopped
    environment:
      - SA_PASSWORD=admin
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - ekinonet

  ekino-api-mr:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ekino-sql-mr,1433;Database=eKino;User=sa;Password=admin;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    networks:
      - ekinonet
    links:
      - ekino-sql-mr
    depends_on:
      - ekino-sql-mr
      
networks:
  ekinonet:
    driver: bridge      